// 完整作者回合编排/时间线/持久化消费者在原创隔离SQL中执行；无模型、无真实存档。
import test from 'node:test'
import assert from 'node:assert/strict'
import {mkdtempSync,writeFileSync,readFileSync,rmSync} from 'node:fs'
import {registerHooks,createRequire} from 'node:module'
import {DatabaseSync} from 'node:sqlite'
import {cleanRollback} from '../lib/clean-rollback.js'
import {installRollbackSync} from '../lib/rollback-sync.js'
import {configureRollbackCleanup} from '../lib/rollback-cleanup.js'
import {SqliteSessionDb} from '../store.js'
import os from 'node:os'
import path from 'node:path'
import {pathToFileURL,fileURLToPath} from 'node:url'
import {createChatSqliteStore} from '../chat-sqlite-store.js'
import {createRollbackGlobalVariables} from '../lib/rollback-global-variables.js'
import {applyRollbackBusinessTurnTransform,applyRollbackBusinessTimelineTransform} from '../deploy/rollback-business-transform.mjs'
import {applyRollbackBodyCommitTurnTransform,applyRollbackBodyCommitHandoffTransform,applyRollbackBodyCommitHostTransform,applyRollbackBodyCommitJobsTransform} from '../deploy/rollback-body-commit-transform.mjs'
import {applyRollbackBodySignalTurnTransform,applyRollbackBodySignalHandoffTransform,applyRollbackBodySignalHostTransform} from '../deploy/rollback-body-signal-transform.mjs'
import {applyForegroundQuiescenceTransform,applySettlementQuiescenceTransform} from '../deploy/rollback-quiescence-transform.mjs'
import {applyRollbackBackgroundOwnerHostTransform} from '../deploy/rollback-background-lifetime-transform.mjs'
import {applyRollbackGlobalHostTransform} from '../deploy/rollback-global-transform.mjs'
import {applyRollbackHostTransform} from '../deploy/rollback-host-transform.mjs'
import {applyRowTimelineTransform} from '../deploy/row-rollback-transform.mjs'
import {applyRollbackSharedBranchTurnTransform} from '../deploy/rollback-shared-branch-transform.mjs'
// 当前离线树缺显示DOM依赖；只给未调用的显示模块装fail-closed占位，不冒充显示/模板渲染验证。
configureRollbackCleanup({sessionEvents:s=>s.snapshotEvents()})
const displayDependencies=registerHooks({resolve(spec,context,next){if(spec==='./tavern-macro-engine.js')return {url:'fixture-macros:unused',shortCircuit:true};if(['jsdom','marked'].includes(spec))return {url:'fixture-display:'+spec,shortCircuit:true};return next(spec,context)},load(url,context,next){if(url==='fixture-macros:unused')return {format:'module',source:"export const renderTavernMacros=()=>{throw Error('本断言禁止调用未打包宏引擎')}",shortCircuit:true};if(url.startsWith('fixture-display:'))return {format:'module',source:"const unavailable=()=>{throw Error('本断言禁止调用显示DOM依赖')};export const JSDOM=unavailable;export const marked=unavailable;export const VirtualConsole=unavailable",shortCircuit:true};return next(url,context)}})
const author=new URL('../../../tools/live-plugin-src/lib/domain/',import.meta.url)
async function fixture(header=true){
 const root=mkdtempSync(path.join(os.tmpdir(),'rollback-turn-consumer-'))
 function module(name,source){const file=path.join(root,name+'.mjs');writeFileSync(file,source,'utf8');return pathToFileURL(file).href}
 const rewrite=source=>source.replace(/from '(.+?)'/g,(all,spec)=>spec.startsWith('./')?'from '+JSON.stringify(new URL(spec,author).href):all)
 const persistence=await import(module('persistence',rewrite(readFileSync(new URL('../../../tmp/plg-standard-1001-code/b/lib/domain/chat-persistence.js',import.meta.url),'utf8'))))
 const timeline=await import(module('timeline',rewrite(applyRollbackBusinessTimelineTransform(applyRowTimelineTransform(readFileSync(new URL('story-timeline.js',author),'utf8')))).replace(new URL('storage-rollback-business.js',author).href,new URL('../lib/rollback-business-state.js',import.meta.url).href)))
 let source=applyRollbackBodySignalTurnTransform(applyRollbackSharedBranchTurnTransform(applyRollbackBusinessTurnTransform(readFileSync(new URL('../../../tmp/rollback-compare-1001/current-turn-orchestration.js',import.meta.url),'utf8'))))
 assert.equal(applyRollbackBodySignalTurnTransform(source),source)
 source=applyRollbackBodyCommitTurnTransform(source);assert.equal(applyRollbackBodyCommitTurnTransform(source),source)
 source=source.replace("import { CARD_MEMORY_TOOLS } from '../../packages/dsh-tavern-card-memory/index.js'",'const CARD_MEMORY_TOOLS=[] // 此测试仅story，不访问card工具')
 source=rewrite(source).replace(new URL('chat-persistence.js',author).href,pathToFileURL(path.join(root,'persistence.mjs')).href).replace(new URL('storage-rollback-business.js',author).href,new URL('../lib/rollback-business-state.js',import.meta.url).href)
 const turn=await import(module('turn',source))
 const helpers={...await import(new URL('copy-json-tree.js',author)),...await import(new URL('json-mutation.js',author)),...await import(new URL('chat-session-state.js',author)),...await import(new URL('tavern-helper-context.js',author)),...await import(new URL('scoped-messages.js',author))}
 const archive=createChatSqliteStore({dataRoot:root,helpers}),chatPersistence=persistence.createChatPersistence({store:archive}),global=createRollbackGlobalVariables({dataRoot:root,profileData:{readJson:async()=>undefined,remove:async()=>{}},archiveForChat:id=>archive.rollbackArchivePath(id)})
 const base={id:'fixture',sessionId:'fixture-session',_storageRevision:1,mode:'story',cardPath:'cards/fixture.json',cardName:'原创卡',messages:[{role:'user',text:'输入52'},{role:'assistant',turn:52,text:'正文52',variables:[{hp:52}]}],variables:{hp:52},unknownBusiness:{keep:'52'}}
 base.openingWorldbookSnapshot={version:1,document:{entries:[{uid:0,content:'原创世界书52'}]},unknown:{keep:true}}
 await archive.update(base.id,()=>base);await global.save({hp:52})
 let fault=true,calls=0,signalUpdateGate;const owners=[],metadata=[],signals=[]
 const store={chatForSession:()=>chatPersistence.read(base.id),readCard:async()=>({name:'原创卡'}),writeChat:async(chat,meta)=>{metadata.push(meta);return chatPersistence.write(chat,meta)},updateChat:async(...args)=>{if(signalUpdateGate)await signalUpdateGate;return chatPersistence.update(...args)},...(header?{writeChatHeader:async(chat,before,meta)=>{metadata.push(meta);return chatPersistence.writeHeader(chat,before,meta)}}:{})}
 const orchestrator=turn.createTurnOrchestrator({store,projectReply:text=>({sourceText:text,projectionText:text,sessionText:text,displayText:text,warnings:[]}),recordRollbackBodySignal:owner=>signals.push(owner),timeline:timeline.createStoryTimeline({readRollbackWorldbook:archive.readRollbackWorldbook,readRollbackWorldbookRef:archive.readCurrentRollbackWorldbookRef}),planner:{plan:async()=>({text:'原创正文规则'})},frameBuilder:{build:input=>({kind:'foreground',...input,userInput:{projectedText:input.inputs[0].projectedText}})},projectUserTemplate:async({chat,turn,text})=>{calls++;const owner={chatId:chat.id,turn,branchId:chat.timeline.branchId};owners.push(owner);assert.equal((await archive.read(base.id)).timeline.branchId,owner.branchId);await global.save({hp:53,old:'旧53'},undefined,owner);if(fault)throw Error('原创模板副SQL提交后失败');return {message:{text},scopes:{local:{hp:53},initial:{hp:52}}}}})
 return {root,archive,global,base,orchestrator,owners,signals,metadata,read:()=>archive.read(base.id),update:chatPersistence.update,setFault:value=>{fault=value},setSignalUpdateGate:value=>{signalUpdateGate=value},calls:()=>calls,cleanup:async()=>{await global.dispose();archive.dispose();assert.equal(path.dirname(path.resolve(root)),path.resolve(os.tmpdir()));assert.ok(path.basename(root).startsWith('rollback-turn-consumer-'));rmSync(root,{recursive:true,force:true})}}
}
for(const header of [true,false])test(`完整实际prepare首次分支模板COMMIT失败与同operation重试${header?'header CAS':'full write'}保原业务基准`,async()=>{
 const f=await fixture(header),input={sessionId:f.base.sessionId,turn:53,userText:'原创53输入',runtimePresetSnapshot:{}}
 try{
  await assert.rejects(f.orchestrator.prepare(input),/副SQL提交后失败/);let chat=await f.read();const body=Object.values(chat.timeline.operations).find(op=>op.kind==='body');assert.equal(body.turn,53);assert.equal(body.status,'running');assert.equal(body.businessBefore.messageCount,2);assert.deepEqual(body.businessBefore.fields.variables,{hp:52});assert.equal(Object.hasOwn(body.businessBefore.fields,'unknownBusiness'),false);assert.equal(chat.messages.at(-1).turn,52);assert.deepEqual(await f.global.read(),{hp:53,old:'旧53'})
  f.setFault(false);const prepared=await f.orchestrator.prepare(input);assert.equal(prepared.ready,true);assert.equal(prepared.frame.turn,53);chat=await f.read();assert.equal(Object.values(chat.timeline.operations).filter(op=>op.kind==='body').length,1);assert.deepEqual(chat.timeline.operations[body.id].businessBefore,body.businessBefore);assert.equal(chat.variables.hp,53)
  await f.orchestrator.prepare(input);assert.equal(f.calls(),2);assert.deepEqual(f.owners[0],f.owners[1]);assert.equal(chat.messages.at(-1).turn,52)
 }finally{await f.cleanup()}
})
test('完整prepare副写失败discard统一物理回退52再prepare新53，实际rc.2 Session及SQL均无旧53',async()=>{
 const f=await fixture(true),requireHost=createRequire(path.join(process.env.DSH_CHECKOUT || 'D:/Program Files (x86)/DSH Desktop/resources/app','package.json'));let native,ctx
 try{
  const raw=readFileSync(new URL('../../../tmp/projection-baseline-1001/clean-session.js',import.meta.url),'utf8').replace(/from "(@deepseek-ai\/[^\"]+)"/g,(_all,name)=>'from '+JSON.stringify(pathToFileURL(requireHost.resolve(name)).href));const file=path.join(f.root,'session.mjs');writeFileSync(file,raw,'utf8');const {Session}=await import(pathToFileURL(file).href)
  const {Context}=await import(pathToFileURL(requireHost.resolve('@deepseek-ai/cordis')).href),{SessionProjectionRegistry}=await import(pathToFileURL(requireHost.resolve('@deepseek-ai/dsh-session-projection')).href),{z}=await import(pathToFileURL(requireHost.resolve('zod')).href);ctx=new Context();const projections=new SessionProjectionRegistry(ctx);projections.register({key:'turnBoundary',stateVersion:1,stateSchema:z.object({lastTurn:z.number()}),init:()=>({lastTurn:0}),apply:(state,e)=>e.type==='turn/end'?{lastTurn:e.data.turn}:state})
  const session=Session.create(f.base.sessionId),append=(turn,text,kind)=>{session.append('turn/start',{turn});session.append('user/message',{id:'u'+turn,role:'user',content:[{type:'text',text}],source:{kind:'user'}},{surfaceOp:'append'});session.append('turn/end',{turn,reason:{kind}})};append(52,'输入52','completed');const keep=session.seq;append(53,'旧53失败输入','error');native=new SqliteSessionDb(path.join(f.root,'session.db'));native.materialize(session.header,session.inheritedEventCount,session.snapshotEvents())
  const input={sessionId:f.base.sessionId,turn:53,userText:'原创53输入',runtimePresetSnapshot:{}};await assert.rejects(f.orchestrator.prepare(input),/副SQL提交后失败/);await f.orchestrator.discard({...input,rollbackBodyOwner:f.signals.at(-1)})
  const oldSignal=f.signals[0],oldOwner=f.owners[0],agent={session,phase:{kind:'idle',lastTurn:53},runtimeContext:{}},meter={states:new WeakMap()},failed=await f.read()
  const {rollbackAvailability}=await import(new URL('rollback-surface.js',author));assert.deepEqual(rollbackAvailability(failed,{events:session.snapshotEvents(),nodes:session.surface.nodes}).failedTurns,[53])
  await f.global.save({hp:99,manual:'用户编辑保留'},await f.global.read())
  await f.update(f.base.id,current=>({...current,guides:[{id:'manual',text:'新的用户要求'}],cardPath:'cards/manually-renamed.json',cardName:'手改卡名',userProfileEnabled:true,userProfileId:'manual',userProfileContextSnapshot:'当前确认画像',cardContextSnapshot:'当前确认画像\n\n卡上下文',macroState:{userName:'手改玩家称呼',local:{new53:'本轮变量'}}}))
  agent.inbox={nextTurn:[],nextStep:[]};let rollbackSync
  installRollbackSync({get:()=>({controlState:{ctx:{sessionProjections:projections},jobsFor:()=>[],broadcast:()=>{}},history:{assistantStreams:new Map()}}),provide:(_key,value)=>{rollbackSync=value}})
  const result=await cleanRollback({chat:failed,requestedTurn:53,availability:rollbackAvailability,readChat:f.read,updateChat:f.update,chats:{rollbackArchivePath:f.archive.rollbackArchivePath,readRollbackWorldbook:f.archive.readRollbackWorldbook,readSlice:f.archive.readSlice,update:f.update},sessions:{get:()=>agent,flush:async()=>{}},persistence:{bindRollbackArchive:async(_id,file)=>native.bindRollbackArchive(file),setRollbackPending:async(_id,value)=>native.setRollbackPending(value),drainOpenHandles:async()=>{},truncateEvents:async(_head,boundary)=>native.truncateFrom(boundary)},services:{projections,projectionCache:{write:async()=>{}},tokenMeterProvider:()=>meter,rollbackSyncProvider:()=>rollbackSync},quiesce:async()=>{},sideCleanup:async()=>{},view:async chat=>({turn:chat.messages.at(-1).turn}),readCard:async()=>({})})
  assert.equal(result.turn,52);assert.equal(agent.phase.lastTurn,52);assert.equal(session.seq,keep);assert.deepEqual(await f.global.read(),{hp:99,manual:'用户编辑保留'});assert.deepEqual((await f.read()).guides,[{id:'manual',text:'新的用户要求'}]);const preserved=await f.read();assert.equal(preserved.cardPath,'cards/manually-renamed.json');assert.equal(preserved.cardName,'手改卡名');assert.equal(preserved.userProfileEnabled,true);assert.equal(preserved.userProfileId,'manual');assert.equal(preserved.cardContextSnapshot,'当前确认画像\n\n卡上下文');assert.deepEqual(preserved.macroState,{userName:'手改玩家称呼'});assert.deepEqual(preserved.unknownBusiness,{keep:'52'});await assert.rejects(f.global.save({old:'延迟旧53'},undefined,oldOwner),/已退役分支/)
  const db=new DatabaseSync(f.archive.rollbackArchivePath(f.base.id));try{assert.ok(!JSON.stringify(db.prepare('SELECT value_json FROM archive_head_fields').all()).includes('旧53'));assert.equal(db.prepare('SELECT count(*) n FROM archive_messages').get().n,2)}finally{db.close()};assert.equal(native.db.prepare('SELECT count(*) n FROM events WHERE seq>=?').get(keep).n,0)
  f.setFault(false);const prepared=await f.orchestrator.prepare(input);assert.equal(prepared.frame.turn,53);assert.notEqual(f.owners.at(-1).branchId,oldOwner.branchId);assert.equal(Object.values((await f.read()).timeline.operations).filter(op=>op.kind==='body').length,1)
  const fresh=await f.read();assert.equal(await f.orchestrator.recordFailure({...input,rollbackBodyOwner:oldSignal,message:'迟到旧53失败'}),false);assert.equal(await f.orchestrator.discard({...input,rollbackBodyOwner:oldSignal}),false);assert.deepEqual(await f.read(),fresh)
  assert.equal(await f.orchestrator.recordFailure({...input,rollbackBodyOwner:f.signals.at(-1),message:'新53当前失败'}),true);assert.equal((await f.read()).foregroundError.message,'新53当前失败')
  const beforeCommit=await f.read(),commitInput={...input,assistantText:'全新53正文',rollbackBodyOwner:f.signals.at(-1)}
  assert.deepEqual(await f.orchestrator.finalize({...commitInput,rollbackBodyOwner:oldSignal,assistantText:'迟到旧53正文'}),{saved:false,reason:'stale-body-owner'});assert.deepEqual(await f.read(),beforeCommit)
  assert.equal((await f.orchestrator.finalize(commitInput)).saved,true);const committed=await f.read();assert.equal(committed.messages.at(-1).turn,53);assert.equal(committed.messages.at(-1).text,'全新53正文');assert.equal(committed.timeline.checkpoints.at(-1).businessBefore.fields.variables.hp,52);assert.equal(committed.messages.length,4)
  assert.equal((await f.orchestrator.finalize(commitInput)).duplicate,true);assert.deepEqual(await f.read(),committed)
  assert.equal((await f.orchestrator.finalize({...commitInput,rollbackBodyOwner:oldSignal})).saved,false);assert.deepEqual(await f.read(),committed)
 }finally{native?.close();await ctx?.fiber.dispose();await f.cleanup()}
})
test('完整实际失败body直重试必须拒绝，不能以副写53后的当前状态替换52基准',async()=>{
 const f=await fixture(true),input={sessionId:f.base.sessionId,turn:53,userText:'原创53输入',runtimePresetSnapshot:{}}
 try{await assert.rejects(f.orchestrator.prepare(input),/副SQL提交后失败/);await f.orchestrator.discard({...input,rollbackBodyOwner:f.signals.at(-1)});const failed=await f.read(),body=Object.values(failed.timeline.operations).find(op=>op.kind==='body');assert.equal(body.status,'failed');await assert.rejects(f.orchestrator.prepare(input),/先.*物理.*清理/);await assert.rejects(f.orchestrator.beginCompatibility(input),/先.*物理.*清理/);assert.deepEqual(await f.read(),failed);assert.equal(f.calls(),1)}finally{await f.cleanup()}
})
test('完整recordFailure与discard锁内核身份：无身份及COMMIT前branch切换不写当前头',async()=>{
 const f=await fixture(true),input={sessionId:f.base.sessionId,turn:53,userText:'原创53输入',runtimePresetSnapshot:{}}
 try{await assert.rejects(f.orchestrator.prepare(input),/副SQL提交后失败/);const signal=f.signals.at(-1),before=await f.read();assert.ok(Object.isFrozen(signal));assert.equal(await f.orchestrator.recordFailure({...input,message:'无身份旧53'}),false);assert.equal(await f.orchestrator.discard(input),false);assert.deepEqual(await f.read(),before)
  let release;f.setSignalUpdateGate(new Promise(resolve=>{release=resolve}));const late=f.orchestrator.recordFailure({...input,rollbackBodyOwner:signal,message:'旧53'});await Promise.resolve()
  await f.update(before.id,current=>{current.timeline.branchId='new-branch';return current});const fresh=await f.read();release();assert.equal(await late,false);assert.equal(await f.orchestrator.discard({...input,rollbackBodyOwner:signal}),false);assert.deepEqual(await f.read(),fresh)
 }finally{await f.cleanup()}
})
test('完整finalize锁前换branch与错operation拒旧正文，当前提交仍正常',async()=>{
 const f=await fixture(true),input={sessionId:f.base.sessionId,turn:53,userText:'原创53输入',runtimePresetSnapshot:{},assistantText:'旧53迟到正文'}
 try{f.setFault(false);await f.orchestrator.prepare(input);const owner=f.signals.at(-1),before=await f.read();assert.equal((await f.orchestrator.finalize(input)).saved,false);assert.equal((await f.orchestrator.finalize({...input,rollbackBodyOwner:{...owner,operationId:'other-op'}})).saved,false);assert.deepEqual(await f.read(),before)
  let release;f.setSignalUpdateGate(new Promise(resolve=>{release=resolve}));const late=f.orchestrator.finalize({...input,rollbackBodyOwner:owner});await Promise.resolve();await f.update(before.id,current=>{current.timeline.branchId='new-branch';return current});const fresh=await f.read();release();assert.equal((await late).saved,false);assert.deepEqual(await f.read(),fresh)
 }finally{await f.cleanup()}
})
test('完整失败信号对同branch错operation、completed与pending均无业务写，当前身份仍记录并discard',async()=>{
 const f=await fixture(true),input={sessionId:f.base.sessionId,turn:53,userText:'原创53输入',runtimePresetSnapshot:{}}
 try{await assert.rejects(f.orchestrator.prepare(input),/副SQL提交后失败/);const signal=f.signals.at(-1),before=await f.read();for(const owner of [{...signal,operationId:'other-op'},{...signal,turn:54},{...signal,sessionId:'other-session'},{...signal,chatId:'other-chat'}]){assert.equal(await f.orchestrator.recordFailure({...input,rollbackBodyOwner:owner,message:'旧53'}),false);assert.equal(await f.orchestrator.discard({...input,rollbackBodyOwner:owner}),false)}assert.deepEqual(await f.read(),before)
  for(const status of ['completed','pending']){await f.update(before.id,current=>{if(status==='completed')current.timeline.operations[signal.operationId].status='completed';else{current.timeline.operations[signal.operationId].status='running';current.rollbackPending={id:'fixture-pending'}}return current});const current=await f.read();if(status==='pending'){await assert.rejects(f.orchestrator.recordFailure({...input,rollbackBodyOwner:signal,message:'旧53'}),/物理回退未完成/);await assert.rejects(f.orchestrator.discard({...input,rollbackBodyOwner:signal}),/物理回退未完成/)}else{assert.equal(await f.orchestrator.recordFailure({...input,rollbackBodyOwner:signal,message:'旧53'}),false);assert.equal(await f.orchestrator.discard({...input,rollbackBodyOwner:signal}),false)}assert.deepEqual(await f.read(),current)}
  await f.update(before.id,current=>{delete current.rollbackPending;return current},{source:'rollback.complete'});assert.equal(await f.orchestrator.recordFailure({...input,rollbackBodyOwner:signal,message:'当前53失败'}),true);assert.equal(await f.orchestrator.discard({...input,rollbackBodyOwner:signal}),true);assert.equal((await f.read()).timeline.operations[signal.operationId].status,'failed')
 }finally{await f.cleanup()}
})
test('实际延迟handoff绑定不可变旧信号不在defer执行时猜新53身份，Host首await前捕获与cleanup清除',async()=>{
 const raw=readFileSync(new URL('../../../tmp/rollback-compare-1001/current-foreground-handoff.js',import.meta.url),'utf8'),source=applyRollbackBodySignalHandoffTransform(applyForegroundQuiescenceTransform(raw));assert.equal(applyRollbackBodySignalHandoffTransform(source),source)
 const {createForegroundHandoff}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));let callback,target;const owner=Object.freeze({chatId:'fixture',sessionId:'s',branchId:'old',operationId:'old-op',turn:53}),input={sessionId:'s',turn:53,reason:'error',rollbackBodyOwner:owner};const handoff=createForegroundHandoff({turns:{finalize(){},discard:async value=>{target=value}},store:{},tasks:{activity(){}},queueBackground(){},defer:fn=>{callback=fn}});handoff.end(input);input.rollbackBodyOwner=Object.freeze({...owner,branchId:'new',operationId:'new-op'});callback();await handoff.whenIdle('s');assert.equal(target.rollbackBodyOwner,owner)
 const host=applyRollbackBodySignalHostTransform(applyRollbackBackgroundOwnerHostTransform(applyRollbackGlobalHostTransform(applyRollbackHostTransform(readFileSync(new URL('../../../tmp/rollback-compare-1001/current-index.js',import.meta.url),'utf8')))));assert.equal(applyRollbackBodySignalHostTransform(host),host);assert.ok(host.includes('recordRollbackBodySignal:owner=>rollbackBodySignals.set(owner.sessionId,owner)'));assert.ok(host.includes('rollbackBodySignals.delete(cut.sessionId)'));assert.ok(host.includes('rollbackBodyOwner:rollbackBodySignals.get(session.id)'));const start=host.indexOf("ctx.on('agent/turn-stopping'");assert.ok(host.indexOf('const rollbackBodyOwner=',start)<host.indexOf('await ',start))
})
test('actual completed延迟排队旧53不启动新53结算，当前completed身份可排队且Host finalize透传',async()=>{
 const source=applyRollbackBodyCommitHandoffTransform(applyRollbackBodySignalHandoffTransform(applyForegroundQuiescenceTransform(readFileSync(new URL('../../../tmp/rollback-compare-1001/current-foreground-handoff.js',import.meta.url),'utf8'))));assert.equal(applyRollbackBodyCommitHandoffTransform(source),source)
 const {createForegroundHandoff}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));const old=Object.freeze({chatId:'fixture',sessionId:'s',turn:53,branchId:'old',operationId:'old-op'}),fresh=Object.freeze({...old,branchId:'new',operationId:'new-op'});let callback,queues=0;const chat={id:'fixture',sessionId:'s',mode:'story',timeline:{branchId:'new',operations:{'new-op':{kind:'body',status:'completed',turn:53,basedOn:{branchId:'new'}}}}};const handoff=createForegroundHandoff({turns:{finalize(){},discard(){}},store:{chatForSession:async()=>chat},tasks:{activity:()=>({role:'settlement',phase:'pending'})},queueBackground:async()=>{queues++},defer:fn=>{callback=fn}})
 for(const owner of [old,undefined,{...fresh,operationId:'wrong'},fresh]){handoff.end({sessionId:'s',turn:53,reason:'completed',rollbackBodyOwner:owner});callback();await handoff.whenIdle('s')}assert.equal(queues,1)
 const raw=readFileSync(new URL('../../../tmp/rollback-compare-1001/current-index.js',import.meta.url),'utf8'),host=applyRollbackBodyCommitHostTransform(applyRollbackBodySignalHostTransform(applyRollbackBackgroundOwnerHostTransform(applyRollbackGlobalHostTransform(applyRollbackHostTransform(raw)))));assert.equal(applyRollbackBodyCommitHostTransform(host),host);assert.ok(host.includes('const saved = await foregroundHandoff.finalize({\n      rollbackBodyOwner,'))
})
test('actual settlement-jobs透传完成owner，Host入run读取后再拒跨branch旧队列无副准备',async()=>{
 const raw=readFileSync(new URL('../../../tmp/rollback-compare-1001/plugin-settlement-jobs.js',import.meta.url),'utf8'),source=applyRollbackBodyCommitJobsTransform(applySettlementQuiescenceTransform(raw));assert.equal(applyRollbackBodyCommitJobsTransform(source),source);const {createSettlementJobs}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'))
 const host=applyRollbackBodyCommitHostTransform(applyRollbackBodySignalHostTransform(applyRollbackBackgroundOwnerHostTransform(applyRollbackGlobalHostTransform(applyRollbackHostTransform(readFileSync(new URL('../../../tmp/rollback-compare-1001/current-index.js',import.meta.url),'utf8'))))));const start=host.indexOf('      if (snapshot === undefined) return'),end=host.indexOf('      snapshot = await prepareNextWorldBookContext(snapshot, signal)',start);assert.ok(start>=0&&end>start);const check=new Function('snapshot','rollbackBodyOwner','readChat','chatId','return (async()=>{'+host.slice(start,end)+'\nreturn true})()')
 const old=Object.freeze({chatId:'fixture',sessionId:'s',turn:53,branchId:'old',operationId:'old-op'}),fresh=Object.freeze({...old,branchId:'new',operationId:'new-op'}),snapshot={id:'fixture',sessionId:'s',timeline:{branchId:'new',operations:{'new-op':{kind:'body',status:'completed',turn:53,basedOn:{branchId:'new'}}}}};let entered=0,settled=0,seen
 const jobs=createSettlementJobs({run:async(_id,_signal,owner)=>{seen=owner;if(await check({messages:[]},owner,async()=>snapshot,'fixture'))entered++;else return false},onSettled:async()=>{settled++}});await jobs.start('fixture',old);assert.equal(seen,old);assert.equal(entered,0);assert.equal(settled,0);await jobs.start('fixture',fresh);assert.equal(seen,fresh);assert.equal(entered,1);assert.equal(settled,1);jobs.dispose();assert.ok(host.includes('settlementJobs.start(chatId,rollbackBodyOwner)'))
})
test('完整实际compatibility首次分支模板失败保正文52与完整前态，重试不改基准',async()=>{
 const f=await fixture(false),input={sessionId:f.base.sessionId,turn:53,userText:'原创53输入',runtimePresetSnapshot:{}}
 try{await assert.rejects(f.orchestrator.beginCompatibility(input),/副SQL提交后失败/);const failed=await f.read(),body=Object.values(failed.timeline.operations).find(op=>op.kind==='body');assert.equal(body.businessBefore.messageCount,2);assert.deepEqual(body.businessBefore.fields.variables,{hp:52});f.setFault(false);assert.equal((await f.orchestrator.beginCompatibility(input)).ready,true);assert.deepEqual((await f.read()).timeline.operations[body.id].businessBefore,body.businessBefore)}finally{await f.cleanup()}
})
