// 预算 / 超时的**单一来源**（host 侧）—— 数字归我们，作者文件只留一行薄缝
//
// 为什么只有 host 侧两项：另外三项（③ 客户端 MVU 下载超时与重试、⑤ 客户端初始化/事件窗口预算、
// ⑭ 开场预览预算）都在 `client.js` 里，而那是**构建产物**（首行即 "Generated by pnpm build:client;
// do not edit directly."）⇒ 浏览器 bundle 无法 import 本包 ⇒ 那三项**只能留字面补丁**。
//
// ⚠ 重要：把数字收进本文件**不会消除缝**（作者文件仍要被改一行去读这里的值）⇒ 上游更新后**仍需重放缝**。
//    它的收益是"**单一来源、一处可审**"（改预算不用再记住每个文件里的字面量），不是"零适配"。
//    真正零适配只有一条路：上游把这几处做成可配置/可注入。
export const BUDGETS = Object.freeze({
  /** ① 卡脚本租约（上游 30000）；实测客户端 MVU 初始化 ≥70s ⇒ 30s 必然 claim-timeout、结算完不成（issues #97）。 */
  scriptClaimMs: 180000,
  /** 服务端模板运行时预算（上游 120000）；大卡（世界书 + MVU + 卡脚本）准备实测整体 46s+。 */
  serverTemplateMs: 900000,
})

/** 取一个预算值；未知名字 fail-loud（避免拼错名字静默拿到 undefined）。 */
export function budget(name) {
  if (!Object.prototype.hasOwnProperty.call(BUDGETS, name)) {
    throw new Error('未知预算名：' + String(name) + '（可用：' + Object.keys(BUDGETS).join(' / ') + '）')
  }
  return BUDGETS[name]
}